"""update book unique constraint

Revision ID: d6f737c6264a
Revises: 635cb2ed0e71
Create Date: 2026-10-06 12:07:24.841907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6f737c6264a'
down_revision: Union[str, Sequence[str], None] = '635cb2ed0e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_book_title', 'books', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_book_title', 'books', type_='unique')
    # ### end Alembic commands ###
